name: CI

on:
  push:
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: energex
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports: ["3306:3306"]
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo_mysql
      - name: Install composer deps
        working-directory: backend-php
        run: |
          composer install --no-interaction --prefer-dist --no-progress
      - name: PHPUnit
        working-directory: backend-php
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: energex
          DB_USERNAME: app
          DB_PASSWORD: app
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          JWT_SECRET: testsecret
        run: vendor/bin/phpunit

  node:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: energex
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports: ["3306:3306"]
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: cache-node
        run: npm ci
      - name: Jest
        working-directory: cache-node
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: energex
          DB_USERNAME: app
          DB_PASSWORD: app
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: npm test -- --runInBand

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        env:
          VITE_API_BASE: http://localhost:8000
        run: npm run build
